export interface DocFrontmatter {
  title: string
  description: string
}

export interface TocEntry {
  id: string
  text: string
  level: number
}

/**
 * Parse YAML frontmatter from a markdown string.
 * Returns the frontmatter fields and the remaining markdown body.
 */
export function parseFrontmatter(markdown: string): { frontmatter: DocFrontmatter; body: string } {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/)
  if (!match) {
    return {
      frontmatter: { title: '', description: '' },
      body: markdown,
    }
  }

  const raw = match[1]
  const body = match[2]

  const frontmatter: DocFrontmatter = { title: '', description: '' }
  for (const line of raw.split('\n')) {
    const colonIndex = line.indexOf(':')
    if (colonIndex === -1) continue
    const key = line.slice(0, colonIndex).trim()
    const value = line.slice(colonIndex + 1).trim()
    if (key === 'title') frontmatter.title = value
    if (key === 'description') frontmatter.description = value
  }

  return { frontmatter, body }
}

/**
 * Extract headings from markdown body text to build a table of contents.
 * Only extracts h2 and h3 headings (## and ###).
 */
export function extractHeadings(markdown: string): TocEntry[] {
  const headings: TocEntry[] = []
  const lines = markdown.split('\n')

  for (const line of lines) {
    const match = line.match(/^(#{2,3})\s+(.+)$/)
    if (!match) continue

    const level = match[1].length
    const text = match[2].trim()
    const id = text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')

    headings.push({ id, text, level })
  }

  return headings
}

/**
 * Generate a slug-safe id from heading text.
 * Must match the IDs generated by the heading renderer in the docs page.
 */
export function headingToId(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
}
